-- =====================================================
-- HEX NOTEBOOK: Checkout Funnel Analytics
-- Copy each section into a separate SQL cell in Hex
-- =====================================================

-- =====================================================
-- CELL 1: FICO Score Dropoff Rates
-- Chart type: Bar chart (X: FICO_SCORE_BUCKET, Y: DROPOFF_PCT)
-- =====================================================
SELECT 
    CASE 
        WHEN FICO_SCORE IS NULL THEN 'No Score'
        WHEN FICO_SCORE < 580 THEN 'Poor (<580)'
        WHEN FICO_SCORE >= 580 AND FICO_SCORE < 670 THEN 'Fair (580-669)'
        WHEN FICO_SCORE >= 670 AND FICO_SCORE < 740 THEN 'Good (670-739)'
        WHEN FICO_SCORE >= 740 AND FICO_SCORE < 800 THEN 'Very Good (740-799)'
        WHEN FICO_SCORE >= 800 THEN 'Exceptional (800+)'
    END as FICO_SCORE_BUCKET,
    COUNT(*) as TOTAL_CHECKOUTS,
    SUM(CASE WHEN IS_APPROVED = 1 THEN 1 ELSE 0 END) as APPROVED,
    SUM(CASE WHEN IS_APPROVED = 1 AND TERM_LENGTH IS NOT NULL THEN 1 ELSE 0 END) as TERM_SELECTED,
    SUM(CASE WHEN IS_APPROVED = 1 AND TERM_LENGTH IS NULL THEN 1 ELSE 0 END) as DROPPED_OFF,
    ROUND(SUM(CASE WHEN IS_APPROVED = 1 AND TERM_LENGTH IS NULL THEN 1 ELSE 0 END) * 100.0 / 
          NULLIF(SUM(CASE WHEN IS_APPROVED = 1 THEN 1 ELSE 0 END), 0), 2) as DROPOFF_PCT
FROM PROD__US.DBT_ANALYTICS.CHECKOUT_FUNNEL_V5
WHERE CHECKOUT_CREATED_DT >= DATEADD(DAY, -30, CURRENT_DATE())
GROUP BY 1
ORDER BY 
    CASE FICO_SCORE_BUCKET
        WHEN 'Exceptional (800+)' THEN 1
        WHEN 'Very Good (740-799)' THEN 2
        WHEN 'Good (670-739)' THEN 3
        WHEN 'Fair (580-669)' THEN 4
        WHEN 'Poor (<580)' THEN 5
        WHEN 'No Score' THEN 6
    END;


-- =====================================================
-- CELL 2: Term Selection vs Confirmation
-- Chart type: Grouped bar (compare CONFIRM_RATE_WITH_TERM vs WITHOUT)
-- =====================================================
SELECT 
    CASE 
        WHEN FICO_SCORE IS NULL THEN 'No Score'
        WHEN FICO_SCORE < 580 THEN 'Poor (<580)'
        WHEN FICO_SCORE >= 580 AND FICO_SCORE < 670 THEN 'Fair (580-669)'
        WHEN FICO_SCORE >= 670 AND FICO_SCORE < 740 THEN 'Good (670-739)'
        WHEN FICO_SCORE >= 740 AND FICO_SCORE < 800 THEN 'Very Good (740-799)'
        WHEN FICO_SCORE >= 800 THEN 'Exceptional (800+)'
    END as FICO_SCORE_BUCKET,
    SUM(CASE WHEN TERM_LENGTH IS NOT NULL THEN 1 ELSE 0 END) as WITH_TERM_SELECTED,
    SUM(CASE WHEN TERM_LENGTH IS NOT NULL AND IS_CONFIRMED = 1 THEN 1 ELSE 0 END) as CONFIRMED_WITH_TERM,
    ROUND(SUM(CASE WHEN TERM_LENGTH IS NOT NULL AND IS_CONFIRMED = 1 THEN 1 ELSE 0 END) * 100.0 / 
          NULLIF(SUM(CASE WHEN TERM_LENGTH IS NOT NULL THEN 1 ELSE 0 END), 0), 2) as CONFIRM_RATE_WITH_TERM,
    SUM(CASE WHEN TERM_LENGTH IS NULL THEN 1 ELSE 0 END) as WITHOUT_TERM_SELECTED,
    SUM(CASE WHEN TERM_LENGTH IS NULL AND IS_CONFIRMED = 1 THEN 1 ELSE 0 END) as CONFIRMED_WITHOUT_TERM,
    ROUND(SUM(CASE WHEN TERM_LENGTH IS NULL AND IS_CONFIRMED = 1 THEN 1 ELSE 0 END) * 100.0 / 
          NULLIF(SUM(CASE WHEN TERM_LENGTH IS NULL THEN 1 ELSE 0 END), 0), 2) as CONFIRM_RATE_WITHOUT_TERM
FROM PROD__US.DBT_ANALYTICS.CHECKOUT_FUNNEL_V5
WHERE CHECKOUT_CREATED_DT >= DATEADD(DAY, -30, CURRENT_DATE())
GROUP BY 1
ORDER BY 
    CASE FICO_SCORE_BUCKET
        WHEN 'Exceptional (800+)' THEN 1
        WHEN 'Very Good (740-799)' THEN 2
        WHEN 'Good (670-739)' THEN 3
        WHEN 'Fair (580-669)' THEN 4
        WHEN 'Poor (<580)' THEN 5
        WHEN 'No Score' THEN 6
    END;


-- =====================================================
-- CELL 3: AOV Dropoff Analysis
-- Chart type: Bar chart (X: AOV_BUCKET, Y: DROPOFF_PCT)
-- =====================================================
SELECT 
    CASE 
        WHEN TOTAL_AMOUNT < 50 THEN 'a. <$50'
        WHEN TOTAL_AMOUNT >= 50 AND TOTAL_AMOUNT < 150 THEN 'b. $50-$150'
        WHEN TOTAL_AMOUNT >= 150 AND TOTAL_AMOUNT < 250 THEN 'c. $150-$250'
        WHEN TOTAL_AMOUNT >= 250 AND TOTAL_AMOUNT < 500 THEN 'd. $250-$500'
        WHEN TOTAL_AMOUNT >= 500 AND TOTAL_AMOUNT < 1000 THEN 'e. $500-$1000'
        WHEN TOTAL_AMOUNT >= 1000 AND TOTAL_AMOUNT < 2000 THEN 'f. $1000-$2000'
        WHEN TOTAL_AMOUNT >= 2000 THEN 'g. $2000+'
    END as AOV_BUCKET,
    COUNT(*) as TOTAL_CHECKOUTS,
    SUM(CASE WHEN IS_APPROVED = 1 THEN 1 ELSE 0 END) as APPROVED,
    SUM(CASE WHEN IS_APPROVED = 1 AND TERM_LENGTH IS NULL THEN 1 ELSE 0 END) as DROPPED_OFF,
    ROUND(SUM(CASE WHEN IS_APPROVED = 1 AND TERM_LENGTH IS NULL THEN 1 ELSE 0 END) * 100.0 / 
          NULLIF(SUM(CASE WHEN IS_APPROVED = 1 THEN 1 ELSE 0 END), 0), 2) as DROPOFF_PCT
FROM PROD__US.DBT_ANALYTICS.CHECKOUT_FUNNEL_V5
WHERE CHECKOUT_CREATED_DT >= DATEADD(DAY, -30, CURRENT_DATE())
GROUP BY 1
ORDER BY 1;


-- =====================================================
-- CELL 4: FICO x AOV Dropoff Matrix
-- Chart type: Heatmap (X: AOV_BUCKET, Y: FICO_GROUP, Color: DROPOFF_PCT)
-- =====================================================
SELECT 
    CASE 
        WHEN FICO_SCORE >= 740 THEN 'High FICO (740+)'
        WHEN FICO_SCORE >= 670 AND FICO_SCORE < 740 THEN 'Good (670-739)'
        WHEN FICO_SCORE >= 580 AND FICO_SCORE < 670 THEN 'Fair (580-669)'
        WHEN FICO_SCORE < 580 THEN 'Poor (<580)'
        ELSE 'No Score'
    END as FICO_GROUP,
    CASE 
        WHEN TOTAL_AMOUNT < 150 THEN '<$150'
        WHEN TOTAL_AMOUNT >= 150 AND TOTAL_AMOUNT < 500 THEN '$150-$500'
        WHEN TOTAL_AMOUNT >= 500 AND TOTAL_AMOUNT < 1000 THEN '$500-$1000'
        WHEN TOTAL_AMOUNT >= 1000 THEN '$1000+'
    END as AOV_BUCKET,
    SUM(CASE WHEN IS_APPROVED = 1 THEN 1 ELSE 0 END) as APPROVED,
    SUM(CASE WHEN IS_APPROVED = 1 AND TERM_LENGTH IS NULL THEN 1 ELSE 0 END) as DROPPED_OFF,
    ROUND(SUM(CASE WHEN IS_APPROVED = 1 AND TERM_LENGTH IS NULL THEN 1 ELSE 0 END) * 100.0 / 
          NULLIF(SUM(CASE WHEN IS_APPROVED = 1 THEN 1 ELSE 0 END), 0), 1) as DROPOFF_PCT
FROM PROD__US.DBT_ANALYTICS.CHECKOUT_FUNNEL_V5
WHERE CHECKOUT_CREATED_DT >= DATEADD(DAY, -30, CURRENT_DATE())
AND FICO_SCORE IS NOT NULL
GROUP BY 1, 2
ORDER BY 
    CASE FICO_GROUP
        WHEN 'High FICO (740+)' THEN 1
        WHEN 'Good (670-739)' THEN 2
        WHEN 'Fair (580-669)' THEN 3
        WHEN 'Poor (<580)' THEN 4
    END, 
    CASE AOV_BUCKET
        WHEN '<$150' THEN 1
        WHEN '$150-$500' THEN 2
        WHEN '$500-$1000' THEN 3
        WHEN '$1000+' THEN 4
    END;


-- =====================================================
-- CELL 5: 0% APR Impact on Conversion ($1000+ Orders)
-- Chart type: Bar chart (X: ZERO_APR_BUCKET, Y: COMPLETION_RATE)
-- =====================================================
SELECT 
    CASE 
        WHEN GREATEST(
            COALESCE(CASE WHEN OFFERED_APR1 = 0 THEN OFFERED_PLAN1_LENGTH ELSE 0 END, 0),
            COALESCE(CASE WHEN OFFERED_APR2 = 0 THEN OFFERED_PLAN2_LENGTH ELSE 0 END, 0),
            COALESCE(CASE WHEN OFFERED_APR3 = 0 THEN OFFERED_PLAN3_LENGTH ELSE 0 END, 0)
        ) = 0 THEN 'a. No 0% APR'
        WHEN GREATEST(
            COALESCE(CASE WHEN OFFERED_APR1 = 0 THEN OFFERED_PLAN1_LENGTH ELSE 0 END, 0),
            COALESCE(CASE WHEN OFFERED_APR2 = 0 THEN OFFERED_PLAN2_LENGTH ELSE 0 END, 0),
            COALESCE(CASE WHEN OFFERED_APR3 = 0 THEN OFFERED_PLAN3_LENGTH ELSE 0 END, 0)
        ) <= 6 THEN 'b. 0% for 1-6 mo'
        WHEN GREATEST(
            COALESCE(CASE WHEN OFFERED_APR1 = 0 THEN OFFERED_PLAN1_LENGTH ELSE 0 END, 0),
            COALESCE(CASE WHEN OFFERED_APR2 = 0 THEN OFFERED_PLAN2_LENGTH ELSE 0 END, 0),
            COALESCE(CASE WHEN OFFERED_APR3 = 0 THEN OFFERED_PLAN3_LENGTH ELSE 0 END, 0)
        ) <= 12 THEN 'c. 0% for 7-12 mo'
        ELSE 'd. 0% for 13+ mo'
    END as ZERO_APR_BUCKET,
    COUNT(*) as TOTAL_APPROVED,
    SUM(CASE WHEN TERM_LENGTH IS NOT NULL THEN 1 ELSE 0 END) as COMPLETED,
    SUM(CASE WHEN TERM_LENGTH IS NULL THEN 1 ELSE 0 END) as DROPPED_OFF,
    ROUND(SUM(CASE WHEN TERM_LENGTH IS NOT NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) as COMPLETION_RATE,
    ROUND(SUM(CASE WHEN TERM_LENGTH IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) as DROPOFF_RATE
FROM PROD__US.DBT_ANALYTICS.CHECKOUT_FUNNEL_V5
WHERE CHECKOUT_CREATED_DT >= DATEADD(DAY, -30, CURRENT_DATE())
    AND TOTAL_AMOUNT >= 1000
    AND IS_APPROVED = 1
GROUP BY 1
ORDER BY 1;


-- =====================================================
-- CELL 6: Summary Metrics (for KPI cards)
-- =====================================================
SELECT 
    COUNT(*) as TOTAL_CHECKOUTS,
    SUM(CASE WHEN IS_APPROVED = 1 THEN 1 ELSE 0 END) as TOTAL_APPROVED,
    SUM(CASE WHEN IS_APPROVED = 1 AND TERM_LENGTH IS NOT NULL THEN 1 ELSE 0 END) as TERM_SELECTED,
    SUM(CASE WHEN IS_APPROVED = 1 AND TERM_LENGTH IS NULL THEN 1 ELSE 0 END) as DROPPED_OFF,
    ROUND(SUM(CASE WHEN IS_APPROVED = 1 AND TERM_LENGTH IS NULL THEN 1 ELSE 0 END) * 100.0 / 
          NULLIF(SUM(CASE WHEN IS_APPROVED = 1 THEN 1 ELSE 0 END), 0), 1) as OVERALL_DROPOFF_PCT,
    SUM(CASE WHEN IS_CAPTURED = 1 THEN 1 ELSE 0 END) as TOTAL_CAPTURED
FROM PROD__US.DBT_ANALYTICS.CHECKOUT_FUNNEL_V5
WHERE CHECKOUT_CREATED_DT >= DATEADD(DAY, -30, CURRENT_DATE());


-- =====================================================
-- CELL 7: Dropoff vs Completed - Terms Comparison
-- =====================================================
SELECT 
    CASE WHEN TERM_LENGTH IS NULL THEN 'Dropped Off' ELSE 'Completed' END as STATUS,
    COUNT(*) as TOTAL,
    ROUND(AVG(OFFERED_APR1) * 100, 1) as AVG_APR1_PCT,
    ROUND(AVG(OFFERED_APR2) * 100, 1) as AVG_APR2_PCT,
    ROUND(AVG(OFFERED_APR3) * 100, 1) as AVG_APR3_PCT,
    ROUND(AVG(OFFERED_PLAN1_LENGTH), 1) as AVG_TERM1_MO,
    ROUND(AVG(OFFERED_PLAN2_LENGTH), 1) as AVG_TERM2_MO,
    ROUND(AVG(OFFERED_PLAN3_LENGTH), 1) as AVG_TERM3_MO,
    ROUND(SUM(CASE WHEN OFFERED_APR1 = 0 OR OFFERED_APR2 = 0 OR OFFERED_APR3 = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) as PCT_WITH_0APR_OFFER,
    ROUND(AVG(
        GREATEST(
            COALESCE(CASE WHEN OFFERED_APR1 = 0 THEN OFFERED_PLAN1_LENGTH ELSE 0 END, 0),
            COALESCE(CASE WHEN OFFERED_APR2 = 0 THEN OFFERED_PLAN2_LENGTH ELSE 0 END, 0),
            COALESCE(CASE WHEN OFFERED_APR3 = 0 THEN OFFERED_PLAN3_LENGTH ELSE 0 END, 0)
        )
    ), 1) as AVG_LONGEST_0APR_TERM
FROM PROD__US.DBT_ANALYTICS.CHECKOUT_FUNNEL_V5
WHERE CHECKOUT_CREATED_DT >= DATEADD(DAY, -30, CURRENT_DATE())
    AND TOTAL_AMOUNT >= 1000
    AND IS_APPROVED = 1
GROUP BY 1
ORDER BY 1 DESC;
